name: sqfentity
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 
publish_to: 'none'

version: 2.3.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^2.1.1
  synchronized: ^3.0.0+2
  path: ^1.8.2
  # sqfentity_gen: '>=2.2.0+5 <3.0.0'
  sqfentity_gen:
    # path: ./../sqfentity_gen
    git:
      url: https://github.com/quicktel-solution/sqfEntity.git
      ref: branch-y
      path: sqfentity_gen
  sqflite_common: ^2.2.1+1
  sqflite_common_ffi: ^2.1.1+1
  meta: ^1.7.0
  

dependency_overrides:
 sqfentity_gen:
   path: ../sqfentity_gen